import tweepy

TWITTER_CONSUMER_KEY = 'IXBsOhx5JVqDH4WiScZnHvJC8'
TWITTER_CONSUMER_SECRET = '8rSBkRBy5CxE1As9S64hnHjctSPkUmZ2GnTvL3MNjoY2DTPVfi'
TWITTER_ACCESS_TOKEN = '1536977498650685440-3pCXHUtEx3m0A9MZji6yWUDQBOceUW'
TWITTER_ACCESS_TOKEN_SECRET = 'JHInPSzHxfd4tdtAp9TyfxDcjKre8H8Y0aGJczVknBoL6'
BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAP0kdwEAAAAA5caCys8AnDktaOytX5szfYD%2FWms%3DsPZBH2OCUXtPR4feADG7sos4frqL9BBj3cGjivJZ0TnpYCSo4A'


def authenticate():
    auth = tweepy.OAuthHandler(TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET)
    auth.set_access_token(TWITTER_ACCESS_TOKEN, TWITTER_ACCESS_TOKEN_SECRET)    
    api = tweepy.API(auth)
    return api

def getClient():
    client = tweepy.Client(bearer_token=BEARER_TOKEN)
    return client
